# *для работы с файлами конфигурации go get -u github.com/spf13/viper

port: "8000"

db:
  username: "postgres"
  password: "qwerty"
  host: "localhost"
  port: "5436"
  dbname: "postgres"
  sslmode: "disable"
